### ISSUE TITLE
Not corrected gcov data in openssl

### ISSUE THREAD

**Issue by 0cherry** [Suresoft-GLaDOS/defects4cpp#63]
Please, check gcov data

**Comment by HansolChoe** [comment]
When running failing test cases'(or all test cases) some gcov data are not correct, as if no test cases were run.

**Comment by HansolChoe** [comment]
Finding reproducible cases...

**Comment by HansolChoe** [comment]
You can reproduce this bug at `openssl`, 15th defect.
If you run failing test case, you can get no gcov files!

This happens because a gcov-build-programs does not dump gcov data(a.k.a `.gcda` files) at abnormal exits.
Hear "abnormal exits" means exiting due to signals.

We should add test cases for detecting gcov files are generated correctly.

I will fix this problem by modifying `test/testutil/main.c`.
